### ISSUE TITLE
Can't download ZIP file

### ISSUE THREAD

**Issue by maximdogonov** [LaunchKit/LaunchKit#19]
Hello! 

Today I install LaunchKit on my VM

All worked fine, but when I try generate ZIP file, I get next screen

![zipproblem](https://cloud.githubusercontent.com/assets/12844960/17680563/d6414376-6351-11e6-81e4-bb8eabe827a3.png)
and nothing. 

I don't see log files. 
How I can debug this issue? 

Thank you!

**Comment by taylorhughes** [comment]
To debug:

- `vagrant ssh` gets you into the machine
- `sudo su -` to become root
- `cd /var/log/upstart/`

In this directory you'll find various logs, some of which will be relevant.
In this case `celery.log` is the one you want to look at to see if you can
find any python stack traces.

**Comment by maximdogonov** [comment]
Thank you! 

I got stay trace: 

[2016-08-15 22:38:47,838: INFO/Worker-2] Uploading archive... (attempt: 3)
[2016-08-15 22:40:25,216: ERROR/Worker-2] Unknown exception during archive upload!
Traceback (most recent call last):
  File "/vagrant/backend/lk/logic/screenshot_bundler.py", line 124, in _write_archive_to_s3
    file_key.set_contents_from_filename(src_filename)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1362, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
    retry_handler=retry_handler
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 104] Connection reset by peer
[2016-08-15 22:40:25,218: INFO/Worker-2] Cleaning up archive...
[2016-08-15 22:40:25,228: ERROR/MainProcess] Task backend.lk.logic.screenshot_bundler._build_and_send_bundle[a985b7da-800a-464d-81e1-a788ade18bc5] raised unexpected: MaxRetriesExceededError("Can't retry backend.lk.logic.screenshot_bundler._build_and_send_bundle[a985b7da-800a-464d-81e1-a788ade18bc5] args:(10,) kwargs:{}",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/vagrant/backend/lk/logic/screenshot_bundler.py", line 194, in _build_and_send_bundle
    raise _build_and_send_bundle.retry()
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 665, in retry
    self.name, request.id, S.args, S.kwargs))
MaxRetriesExceededError: Can't retry backend.lk.logic.screenshot_bundler._build_and_send_bundle[a985b7da-800a-464d-81e1-a788ade18bc5] args:(10,) kwargs:{}

**Comment by maximdogonov** [comment]
but, I check S3 keys with ./s3cmd, they valid!

MacBook-Pro-Andrey:s3cmd-1.6.1 andrey$ ./s3cmd ls
2016-02-10 06:32 s3://elasticbeanstalk-us-east-1-933321346638
2016-02-15 14:00 s3://elasticbeanstalk-us-west-2-933321346638
2016-08-11 10:19 s3://launchkit1
MacBook-Pro-Andrey:s3cmd-1.6.1 andrey$ ./s3cmd rm s3://launchkit1/IMG_0265.PNG
delete: 's3://launchkit1/IMG_0265.PNG'
MacBook-Pro-Andrey:s3cmd-1.6.1 andrey$ ./s3cmd put ~/Downloads/IMG_0265.PNG s3://launchkit1/
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: '/Users/andrey/Downloads/IMG_0265.PNG' -> 's3://launchkit1/IMG_0265.PNG' [1 of 1]
1688891 of 1688891 100% in 1s 1618.76 kB/s done
upload: '/Users/andrey/Downloads/IMG_0265.PNG' -> 's3://launchkit1/IMG_0265.PNG' [1 of 1]
1688891 of 1688891 100% in 0s 1686.54 kB/s done
MacBook-Pro-Andrey:s3cmd-1.6.1 andrey$ 
показать все bucket'ы

**Comment by maximdogonov** [comment]
vim /vagrant/backend/lk/logic/screenshot_bundler.py
Line:73
def _signed_s3_download_url(url, file_basename):
  connection = S3Connection(settings.READONLY_S3_ACCESS_KEY_ID,
        settings.READONLY_S3_SECRET_ACCESS_KEY**,host="s3-eu-west-1.amazonaws.com"**)
  archives_bucket = Bucket(connection=connection, name=settings.BUNDLES_S3_BUCKET_NAME)

Line:113
def _write_archive_to_s3(bundle, src_filename):
  connection = S3Connection(settings.READWRITE_S3_ACCESS_KEY_ID,
      settings.READWRITE_S3_SECRET_ACCESS_KEY**,host="s3-eu-west-1.amazonaws.com"**)

**Comment by maximdogonov** [comment]
This my solution!

**Comment by taylorhughes** [comment]
Ah so the bucket location is tied to some default configuration, hmph. Would be nice to put that in the config as well.
